/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * VHG Tailor API
 * API documentation
 * OpenAPI spec version: 1.3
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { HeroSectionResponseDto, ImageDto } from "../../model";
import { customInstance } from "../../mutator/custom-instance";

export const heroSectionControllerGetHeroSection = (signal?: AbortSignal) => {
  return customInstance<HeroSectionResponseDto>({
    url: `/hero-section`,
    method: "GET",
    signal,
  });
};

export const getHeroSectionControllerGetHeroSectionQueryKey = () => {
  return [`/hero-section`] as const;
};

export const getHeroSectionControllerGetHeroSectionQueryOptions = <
  TData = Awaited<ReturnType<typeof heroSectionControllerGetHeroSection>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof heroSectionControllerGetHeroSection>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getHeroSectionControllerGetHeroSectionQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof heroSectionControllerGetHeroSection>>
  > = ({ signal }) => heroSectionControllerGetHeroSection(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof heroSectionControllerGetHeroSection>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HeroSectionControllerGetHeroSectionQueryResult = NonNullable<
  Awaited<ReturnType<typeof heroSectionControllerGetHeroSection>>
>;
export type HeroSectionControllerGetHeroSectionQueryError = unknown;

export function useHeroSectionControllerGetHeroSection<
  TData = Awaited<ReturnType<typeof heroSectionControllerGetHeroSection>>,
  TError = unknown,
>(options: {
  query: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof heroSectionControllerGetHeroSection>>,
      TError,
      TData
    >
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof heroSectionControllerGetHeroSection>>,
        TError,
        TData
      >,
      "initialData"
    >;
}): DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useHeroSectionControllerGetHeroSection<
  TData = Awaited<ReturnType<typeof heroSectionControllerGetHeroSection>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof heroSectionControllerGetHeroSection>>,
      TError,
      TData
    >
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof heroSectionControllerGetHeroSection>>,
        TError,
        TData
      >,
      "initialData"
    >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };
export function useHeroSectionControllerGetHeroSection<
  TData = Awaited<ReturnType<typeof heroSectionControllerGetHeroSection>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof heroSectionControllerGetHeroSection>>,
      TError,
      TData
    >
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey };

export function useHeroSectionControllerGetHeroSection<
  TData = Awaited<ReturnType<typeof heroSectionControllerGetHeroSection>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof heroSectionControllerGetHeroSection>>,
      TError,
      TData
    >
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions =
    getHeroSectionControllerGetHeroSectionQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const heroSectionControllerCreateHeroSection = (
  imageDto: ImageDto[],
) => {
  return customInstance<void>({
    url: `/hero-section`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: imageDto,
  });
};

export const getHeroSectionControllerCreateHeroSectionMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof heroSectionControllerCreateHeroSection>>,
    TError,
    { data: ImageDto[] },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof heroSectionControllerCreateHeroSection>>,
  TError,
  { data: ImageDto[] },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof heroSectionControllerCreateHeroSection>>,
    { data: ImageDto[] }
  > = (props) => {
    const { data } = props ?? {};

    return heroSectionControllerCreateHeroSection(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type HeroSectionControllerCreateHeroSectionMutationResult = NonNullable<
  Awaited<ReturnType<typeof heroSectionControllerCreateHeroSection>>
>;
export type HeroSectionControllerCreateHeroSectionMutationBody = ImageDto[];
export type HeroSectionControllerCreateHeroSectionMutationError = unknown;

export const useHeroSectionControllerCreateHeroSection = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof heroSectionControllerCreateHeroSection>>,
    TError,
    { data: ImageDto[] },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof heroSectionControllerCreateHeroSection>>,
  TError,
  { data: ImageDto[] },
  TContext
> => {
  const mutationOptions =
    getHeroSectionControllerCreateHeroSectionMutationOptions(options);

  return useMutation(mutationOptions);
};
export const heroSectionControllerUpdateHeroSection = (
  imageDto: ImageDto[],
) => {
  return customInstance<void>({
    url: `/hero-section`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: imageDto,
  });
};

export const getHeroSectionControllerUpdateHeroSectionMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof heroSectionControllerUpdateHeroSection>>,
    TError,
    { data: ImageDto[] },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof heroSectionControllerUpdateHeroSection>>,
  TError,
  { data: ImageDto[] },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof heroSectionControllerUpdateHeroSection>>,
    { data: ImageDto[] }
  > = (props) => {
    const { data } = props ?? {};

    return heroSectionControllerUpdateHeroSection(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type HeroSectionControllerUpdateHeroSectionMutationResult = NonNullable<
  Awaited<ReturnType<typeof heroSectionControllerUpdateHeroSection>>
>;
export type HeroSectionControllerUpdateHeroSectionMutationBody = ImageDto[];
export type HeroSectionControllerUpdateHeroSectionMutationError = unknown;

export const useHeroSectionControllerUpdateHeroSection = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof heroSectionControllerUpdateHeroSection>>,
    TError,
    { data: ImageDto[] },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof heroSectionControllerUpdateHeroSection>>,
  TError,
  { data: ImageDto[] },
  TContext
> => {
  const mutationOptions =
    getHeroSectionControllerUpdateHeroSectionMutationOptions(options);

  return useMutation(mutationOptions);
};
