/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * VHG Tailor API
 * API documentation
 * OpenAPI spec version: 1.3
 */
import type { ImageDto } from "./imageDto";

export interface BlogResponse {
  /** Nội dung của blog */
  content: string;
  /** Cover image data */
  coverImage: ImageDto;
  /** Tiêu đề blog */
  title: string;
}
