/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * VHG Tailor API
 * API documentation
 * OpenAPI spec version: 1.3
 */

export interface BlogDTO {
  /** Content of the blog */
  content: string;
  /** Cover image */
  coverImage: string;
  /** Tittle of the blog */
  title: string;
}
