/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * VHG Tailor API
 * API documentation
 * OpenAPI spec version: 1.3
 */

export interface BlogResponseDto {
  /** Tên tác giả viết blog */
  author: string;
  /** Nội dung của blog */
  content: string;
  /** URL của hình ảnh */
  coverImage: string;
  /** Blog duoc tao luc */
  createdAt: string;
  /** Id của blog */
  id: string;
  /** Slug cua blog */
  slug: string;
  /** Tiêu đề blog */
  title: string;
}
