/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * VHG Tailor API
 * API documentation
 * OpenAPI spec version: 1.3
 */
import type { BlogResponseDto } from "./blogResponseDto";

export interface BlogListResponseDto {
  /** Dữ liệu chứa danh sách blogs */
  data: BlogResponseDto[];
  /** Trạng thái của yêu cầu */
  status: number;
}
