/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * VHG Tailor API
 * API documentation
 * OpenAPI spec version: 1.3
 */
import type { BlogResponse } from "./blogResponse";

export interface BlogResponseDto {
  /** Dữ liệu chứa danh sách blogs */
  data: BlogResponse;
  /** Trạng thái của yêu cầu */
  status: number;
}
