/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * VHG Tailor API
 * API documentation
 * OpenAPI spec version: 1.3
 */

export interface ChangePasswordDto {
  /** New password of the user */
  newPassword: string;
  /** Current password of the user */
  oldPassword: string;
  /** Username of the user */
  username: string;
}
