/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * VHG Tailor API
 * API documentation
 * OpenAPI spec version: 1.3
 */
import type { ImageDto } from "./imageDto";

export interface CreateProductDto {
  /** Description of the product */
  description: string;
  /** Image details for the product */
  images: ImageDto[];
  /** Link to buy product */
  link: string;
  /** Main image URL of the product */
  material: string;
  /** Name of the product */
  name: string;
  /** Price of the product */
  price: number;
  /** Available sizes of the product */
  sizes: string[];
  /** ID of the product type (e.g., 1 for Clothing) */
  typeId: number;
}
