/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * VHG Tailor API
 * API documentation
 * OpenAPI spec version: 1.3
 */

export interface CreateProductDto {
  /** Description of the product */
  description: string;
  /** Main image URL of the product */
  image: string;
  /** Image URLs for the product */
  images: string[];
  /** Material of the product */
  material: string;
  /** Name of the product */
  name: string;
  /** Price of the product */
  price: number;
  /** Available sizes of the product */
  sizes: string[];
  /** Slug for the product, auto-generated from name */
  slug: string;
  /** ID of the product type (e.g., 1 for Clothing) */
  typeId: number;
}
