/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * VHG Tailor API
 * API documentation
 * OpenAPI spec version: 1.3
 */

export interface HeroSectionResponseDto {
  data: string[];
  /** Status number */
  status: number;
}
