/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * VHG Tailor API
 * API documentation
 * OpenAPI spec version: 1.3
 */
import type { ImageResponseDto } from "./imageResponseDto";

export interface HeroSectionResponseDto {
  data: ImageResponseDto[];
  /** Status number */
  status: number;
}
