/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * VHG Tailor API
 * API documentation
 * OpenAPI spec version: 1.3
 */

export interface ImageResponseDto {
  /** Public ID của hình ảnh từ Cloudinary hoặc dịch vụ tương tự */
  public_id: string;
  /** URL của hình ảnh */
  url: string;
}
