/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * VHG Tailor API
 * API documentation
 * OpenAPI spec version: 1.3
 */
import type { ImagesControllerUploadFile200DataItem } from "./imagesControllerUploadFile200DataItem";

export type ImagesControllerUploadFile200 = {
  data?: ImagesControllerUploadFile200DataItem[];
  message?: string;
  status?: number;
};
