/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * VHG Tailor API
 * API documentation
 * OpenAPI spec version: 1.3
 */

export interface ImageDto {
  /** Public ID of the image from Cloudinary or similar service */
  public_id: string;
  /** URL of the image */
  url: string;
}
