/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * VHG Tailor API
 * API documentation
 * OpenAPI spec version: 1.3
 */

export interface TResponseFindAllType {
  /** Dữ liệu chứa danh sach kieu san pham */
  data: string[];
  /** Trạng thái của yêu cầu */
  status: string;
}
