/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * VHG Tailor API
 * API documentation
 * OpenAPI spec version: 1.3
 */

export interface UserDto {
  /** Id của người dùng */
  id: string;
  /** Tên người dùng */
  name: string;
  /** Tên đăng nhập */
  username: string;
}
