/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * VHG Tailor API
 * API documentation
 * OpenAPI spec version: 1.3
 */

export interface UserProfileDto {
  exp: number;
  iat: number;
  name: string;
  sub: number;
  username: string;
}
