/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * VHG Tailor API
 * API documentation
 * OpenAPI spec version: 1.3
 */
import type { UserDto } from "./userDto";

export interface UsersResponseDto {
  /** Danh sách người dùng */
  data: UserDto[];
  /** Status number */
  status: number;
}
